#!/bin/bash
FILE=`tempfile -p qr- -s .png`
xsel -b -o | qrencode -o $FILE
echo Contents:
xsel -b -o
echo
echo 'Showing the QR code, press <ESC> to exit.'
display $FILE
# Downloaded from https://bram.xyz/blog/2012/04/clipboard-%E2%86%92-qr-code-in-console/
